deps/ffmpeg.json
deps/fluidsynth.json
deps/fmt.json
deps/libmariadbclient.json
tv.kodi.Kodi.json

Just a merge of @tilosp pull requests 6-10. Please check @comparascope 
Close #6 
Close #7
Close #8
Close #9
Close #10

Multimerge from @tilosp lib updates

---

Makefile

Makefile was broken by fdc31036e6222cd07d607133ef2bbf01bb091f9d

fix Makefile after change to yaml manifest

---

deps/pycryptodome.json
deps/python-pillow.json
deps/simplejson.json
tv.kodi.Kodi.yml

It is needed for Netflix plugin (https://github.com/asciidisco/plugin.video.netflix)

Add pycryptodome, python-pillow and simplejson

---

tv.kodi.Kodi.yml

Allow access to org.freedesktop.ScreenSaver

---

deps/python-pillow.json

fix udev build error

---

deps/pycryptodome.json
deps/python-pillow.json
deps/rapidxml.json
deps/simplejson.json
tv.kodi.Kodi.yml

addons: add pvr.iptvsimple

---

tv.kodi.Kodi.appdata.xml
tv.kodi.Kodi.yml

This was missed when app itself was updated.

Update to 18.7

---

deps/libinput.yml
tv.kodi.Kodi.yml

This updates the beta branch to the latest Matrix version 19.0b2.

Update to Matrix 19.0b2

---

addons/imagedecoder.heif/imagedecoder.heif.json
modules/dav1d/dav1d.json
modules/ffmpeg/ffmpeg.json
tv.kodi.Kodi.yml

revert FFmpeg to supported release, add AV1 decoding

---

addons/inputstream.adaptive/inputstream.adaptive.json

update inputstream.adaptive to current Matrix/stable version

addons: update inputstream.adaptive

---

README.md

Addressed: https://github.com/flathub/tv.kodi.Kodi/pull/118#issuecomment-945015101

docs(README.md): Add note about shared-modules

---

README.md
addon-manifest.xml.patch
addons/game.libretro.mrboom/game.libretro.mrboom.json
tv.kodi.Kodi.yml

testing an alternative to #142

try to fix Mrboom

---

addons/audiodecoder.dumb/audiodecoder.dumb.json
kodi.sh.in.patch
tv.kodi.Kodi.yml

Closes https://github.com/flathub/tv.kodi.Kodi/issues/152

Update to kodi 19.4

---

addons-no-startupenable.patch
addons/game.libretro/game.libretro.json
addons/visualization.pictureit/visualization.pictureit.json
tv.kodi.Kodi.yml

Update kodi version and  all included binary addons. Motivation is to pull in these steam deck changes https://github.com/xbmc/peripheral.joystick/pull/234

Update to latest version

---

modules/avahi/avahi.json
modules/libplist/libplist.json
modules/shairplay/shairplay.json
tv.kodi.Kodi.yml

This PR enables AirPlay support and closes #186.

AirPlay support

---

tv.kodi.Kodi.yml

Allow to access lirc on filesystem

---

tv.kodi.Kodi.yml

Reverts flathub/tv.kodi.Kodi#241

Revert "Add PipeWire support"

---

addons/imagedecoder.heif/imagedecoder.heif.json
tv.kodi.Kodi.yml
waylandpp-gcc13.patch

Closes https://github.com/flathub/tv.kodi.Kodi/pull/220
Closes https://github.com/flathub/tv.kodi.Kodi/issues/255

Use fsdk 23.08 runtime

---

patches/libbdplus-gpg-error.patch
tv.kodi.Kodi.yml

Hopefully helps running blurays

Add libaacs and libbdplus

---

tv.kodi.Kodi.yml

Updated the URL for the libcdio, updated to 2.2.0 with hash;
lines 324, 325, 329

Change libcdio url and update

---

addons/game.libretro.mrboom/game.libretro.mrboom.json

I think this is saner, cf. https://stackoverflow.com/a/21819360/7196903.

Limit nr of jobs for make
