flathub/tv.kodi.Kodi

- tv.kodi.Kodi.json
This makes is easier to update the dependencies, because only url and sha256 needs to be changed
> Remove version from dest-filename

- deps/ffmpeg.json
This enables gnutls support in ffmpeg. This is needed for many https streams.
Still needs testing.
> enable TLS support in ffmpeg (fixes #32)

- deps/fmt.json
This reverts commit 2501db9d936e39b2a7c4a56496c4ac78b00ba672.
see https://github.com/flathub/tv.kodi.Kodi/issues/36
I didn't verify this fixes the issue yet, so lets try the test build when it's done
> Revert "Update fmt to 5.3.0"

- tv.kodi.Kodi.yml
OpenJDK 10 is EOL
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10#deprecated
> Bump OpenJDK to 11

- deps/libopenmpt.json
`libopenmpt.a` weights 113MB (whole kodi flatpak is 429.5 MB) and shouldn't be needed for anything. Shared libs should be sufficient.
> Disable some static libs

- deps/libmariadbclient.json
The MariaDB C connector failed to download. I visited the site, found a correct URL for a newer version on the 3.0 series, and swapped them out.
> Use a link for the MariaDB C connector that actually works.

- tv.kodi.Kodi.appdata.xml
- tv.kodi.Kodi.yml
https://kodi.tv/article/kodi-leia-188-release
- Fixes a severe security issue in gnutls
- Other significant library/compatibility updates
- Gets client/server on MariaDB 10.5.4 working for Android
- Fixes video database access for Ubuntu 20.4 and other distros using earlier libfmt versions (search and other filtering failed)
- Fixes subtitle handling from archives
- Fixes CDDB access
- Makes minor improvements to logging and memory reporting/display
- Fixes EDLs where skip points are at the very start of a file
- Contains code improvements to fix specific events, e.g. race conditions in the EPG or "pause" on end of streams on Android
- Enables alpha blending for the video player (Windows)
- Better handles specific exceptions (Android, mostly)
> Update to 18.8 Leia

- addons/audiodecoder.fluidsynth/audiodecoder.fluidsynth.json
`fluidsynth2` [available](https://github.com/flathub/shared-modules/blob/master/linux-audio/fluidsynth2.json) now in `shared-modules`. Would be nice to switch on this version. Thanks.
> Switch to shared-modules version of fluidsynth2 module

- kodi.sh.in.patch
Otherwise the crashlog will be written to the host folder, which we
usually don't expose in the flatpak (for good reasons).
This means, that it won't be written.
> Patch crashlog dir

- addon-manifest.xml.patch
- addons-no-startupenable.patch
- tv.kodi.Kodi.yml
enabling pvr addons by default causes crashing with a clean user data dir.
also see https://forum.kodi.tv/showthread.php?tid=366614
> don't enable pvr addons automatically

- tv.kodi.Kodi.yml
The org.freedesktop.Sdk.Extension.openjdk was supposed to contain a rolling openjdk version but it's currently stuck at v17 (latest is v19). Kodi flatpak uses it since https://github.com/flathub/tv.kodi.Kodi/commit/6ae4295fe3eb40d7966658d2e468f7333a31ba0d but I don't see any particular reason to always use latest openjdk (does kodi guarantee compatibility with each new release?
Using org.freedesktop.Sdk.Extension.openjdk17 (latest LTS version) explicitly may be better choice. Kodi could move to another version when it wants to and this also unblocks moving to 22.08 runtime.
Cherry-pick of @Erick555 work in https://github.com/flathub/tv.kodi.Kodi/pull/178 targeting beta now
> Use openjdk 17 explicitly

- tv.kodi.Kodi.yml
This is a reminder to reenable fishbmc when https://github.com/xbmc/visualization.fishbmc/pull/55 is merged
> Reenable fishbmc

- modules/dav1d/dav1d.json
Removing libraries after build makes this unusable
Fixes https://github.com/flathub/tv.kodi.Kodi/issues/206
> libdav1d: stop removing libraries

- Makefile
This makes sure the return code when the build-step fails is non-zero
> Makefile: Handle error in build properly

- Makefile
In certain cases, for example if the variable is empty for some reason, it might cause problems. Adding additional escaping prevents this.
> Escape PIPESTATUS in Makefile

- tv.kodi.Kodi.yml
The `-DENABLE_PIPEWIRE=ON` is optional as PipeWire is already build but I guess it doesn't hurt.
Fixes #240.
> Add PipeWire support

- tv.kodi.Kodi.yml
That's the same version the internal Kodi FFmpeg build uses.
Fixes https://github.com/xbmc/xbmc/issues/25143.
> Bump FFmpeg to version 6.0.1

- tv.kodi.Kodi.yml
Fixes #228, although not perfect as hot plugging doesn't work.
> Allow read-only access to /run/udev to make input with GBM work

- addons/inputstream.adaptive/inputstream.adaptive.json
The currently used inputstream.adaptive 21.4.4-Omega has a lot of MPEG Dash bugs e.g. broken live streaming support. https://github.com/xbmc/inputstream.adaptive/issues/1517
So it would be nice to update it to latest inputstream.adaptive 21.4.9-Omega.
> Update inputstream.adaptive to 21.4.9-Omega

- tv.kodi.Kodi.yml
Fixes outdated url-templates.
libinput has relocated releases
libcec version in anitya is actually of the format "libcec-x.x.x"
> x-checker-data Anitya fixes

- tv.kodi.Kodi.yml
a number of libs will install into lib64 on a 64bit system. This splits some in lib, and others in lib64. Failures were occuring for some find_package calls (pugixml). As flatpak is bundled, just set all locations to lib regardless.
I attempted to change search paths, but this just ended up being the easier/cleaner solution.
Note: exiv2 will want this for piers
> set CMAKE_INSTALL_LIBDIR to force lib location
